void __fastcall sub_FB9E0(int a1, int a2)
{
  char *v4; // r9
  char *v5; // r1
  int v6; // r0
  const char *v7; // r3
  int v8; // r5
  int v9; // r4
  int v10; // r0
  const char **v11; // r8
  int v12; // r4
  int v13; // r10
  int v14; // r7
  int v15; // r0
  int v16; // r0
  int v17; // r7
  int v18; // r0
  _DWORD *v19; // r0
  void *v20; // r4
  const char *v21; // r0
  const char *v22; // r1
  int v23; // r0
  int v24; // r4
  unsigned int v25; // r0
  unsigned int v26; // r5
  char *v27; // r6
  const char *v28; // r0
  __int64 v29; // r0
  int v30; // r0
  int v31; // r0
  int v32; // r0
  int v33; // r0
  int v34; // r3
  char *v35; // r0
  void *v36; // r4
  int v37; // r0
  int v38; // r0
  const char *v39; // r0
  const char *v40; // r4
  int v41; // r0
  const char *v42; // r0
  _DWORD *v43; // [sp+Ch] [bp-20h]
  _DWORD v44[5]; // [sp+10h] [bp-1Ch] BYREF
  int v45; // [sp+24h] [bp-8h] BYREF

  sub_231DD4(a2);
  if ( !a1 )
  {
    if ( dword_47ACB8 )
      sub_94708("No core file specified.  (Use `detach' to stop debugging a core file.)");
    sub_94708("No core file specified.");
  }
  v4 = (char *)sub_29B938(a1);
  if ( *v4 != 47 )
  {
    v34 = sub_31E2A4(dword_48A4F8, &word_39899C, v4);
    v35 = v4;
    v4 = (char *)v34;
    free(v35);
  }
  v5 = (char *)&loc_20000 + 2;
  if ( !dword_475508 )
    v5 = (_BYTE *)&loc_20000;
  v6 = sub_967DC((int)v4, (int)v5);
  if ( v6 < 0 )
    sub_258B2C(v4);
  v7 = "rb";
  if ( dword_475508 )
    v7 = "r+b";
  sub_162E4C(&v45, v4, dword_47ACA8, v7, v6);
  if ( !v45 )
    sub_258B2C(v4);
  if ( !sub_2AA894(v45, 3) )
  {
    v8 = v45;
    v9 = dword_47AD08;
    if ( !dword_47AD08 )
    {
LABEL_50:
      v38 = sub_2A6938(0);
      v39 = (const char *)sub_2A6948(v38);
      sub_94708("\"%s\" is not a core dump: %s", v4, v39);
    }
    while ( !(*(int (__fastcall **)(int))(v9 + 4))(v8) )
    {
      v9 = *(_DWORD *)(v9 + 16);
      if ( !v9 )
        goto LABEL_50;
    }
  }
  sub_231C90(&unk_47AD0C);
  dword_47ACB8 = v45;
  v45 = 0;
  v43 = sub_92564((int)sub_FB9D8, 0);
  v10 = sub_B834C(dword_47ACB8);
  v11 = (const char **)dword_47ACB8;
  dword_47ACBC = v10;
  if ( v10 && ((int (*)(void))loc_16B198)() )
  {
    v13 = 0;
  }
  else
  {
    v12 = dword_47AD08;
    if ( !dword_47AD08 )
      goto LABEL_47;
    v13 = 0;
    v14 = 0;
    do
    {
      v15 = (*(int (__fastcall **)(int, const char **))(v12 + 8))(v12, v11);
      if ( v15 )
        v13 = v12;
      v12 = *(_DWORD *)(v12 + 16);
      if ( v15 )
        ++v14;
    }
    while ( v12 );
    if ( v14 > 1 )
    {
      sub_946D8("\"%s\": ambiguous core format, %d handlers match", *v11, v14);
      goto LABEL_26;
    }
    if ( !v14 )
LABEL_47:
      sub_94708("\"%s\": no core file handler recognizes format", *v11);
  }
LABEL_26:
  dword_47AD04 = v13;
  sub_FA5D0();
  dword_47AD00 = (int)sub_930BC(1u, 8u);
  v16 = sub_948EC(dword_47ACB8, (void **)dword_47AD00, (_DWORD *)(dword_47AD00 + 4));
  if ( v16 )
  {
    v40 = *(const char **)dword_47ACB8;
    v41 = sub_2A6938(v16);
    v42 = (const char *)sub_2A6948(v41);
    sub_94708("\"%s\": Can't find sections: %s", v40, v42);
  }
  if ( !*(_DWORD *)(dword_487D2C + 8) )
    sub_B839C(dword_47ACB8);
  sub_231BA0(&unk_47AD0C);
  sub_92668(v43);
  sub_23E17C();
  dword_4878EC = dword_475848;
  dword_4878F0 = dword_47584C;
  dword_4878F4 = dword_475850;
  sub_1DDD1C(dword_475848);
  v17 = dword_47ACB8;
  v18 = sub_2AD7D4(dword_47ACB8, ".reg");
  sub_2ADD24(v17, sub_FBF8C, v18);
  if ( sub_98FA0(&dword_4878EC, &dword_475848) )
  {
    v19 = (_DWORD *)sub_23E6D8(-1);
    if ( v19 )
    {
      sub_23FA18(v19[2], v19[3], v19[4]);
    }
    else
    {
      v37 = sub_1836B0(0);
      sub_1839C0(v37, 1);
      sub_98F78(v44, 1);
      dword_4878EC = v44[0];
      dword_4878F0 = v44[1];
      dword_4878F4 = v44[2];
      ((void (*)(void))loc_23FAB4)();
    }
  }
  sub_17FFFC(&unk_47AD0C, a2);
  v20 = sub_92E50();
  sub_231ECC();
  sub_92E68((int)v20);
  v21 = (const char *)sub_2A9FA0(dword_47ACB8);
  v22 = v21;
  if ( v21 )
    v21 = (const char *)sub_259F38("Core was generated by `%s'.\n", v21);
  sub_189584(v21, v22);
  v23 = sub_2A9FD0(dword_47ACB8);
  v24 = v23;
  if ( v23 > 0 )
  {
    if ( dword_47ACBC && ((int (*)(void))loc_16C88C)() )
      v25 = ((int (__fastcall *)(int, int))loc_16C8D8)(dword_47ACBC, v24);
    else
      v25 = sub_99B14(v24);
    v26 = v25;
    v27 = sub_99A74(v25);
    v28 = sub_99A50(v26);
    sub_259F38("Program terminated with signal %s, %s.\n", v27, v28);
    v29 = sub_26CC1C("_exitsignal");
    v23 = sub_26CCA8(v29, HIDWORD(v29), v24, v24 >> 31);
  }
  v30 = sub_1DDBE4(v23);
  v31 = sub_2322DC(v30, -1);
  sub_15D7A0(v31);
  v32 = sub_15F810(0);
  v33 = sub_20E810(v32, 1, 1);
  if ( sub_23E520(v33) > 1 )
  {
    v36 = sub_92E50();
    sub_240664(0, a2);
    sub_92E68((int)v36);
  }
  if ( v45 )
    ((void (*)(void))loc_1625D0)();
  free(v4);
}
