/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall axi_fpga_dev_open(inode *inode, file *filp);
loff_t __fastcall axi_fpga_dev_llseek(file *filp, loff_t offset, int whence);
int __fastcall axi_fpga_dev_mmap(file *filp, vm_area_struct *vma);
ssize_t __fastcall axi_fpga_dev_read(file *f, char *buf, size_t len, loff_t *ppos);
__int64 axi_fpga_dev_release();
int __cdecl axi_fpga_dev_init();
void __cdecl axi_fpga_dev_exit();
// __int64 __fastcall misc_deregister(_QWORD); weak
// int __fastcall remap_pfn_range(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall memremap(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall _arch_copy_to_user(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall memunmap(_QWORD); weak
// __int64 __fastcall _memset_io(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall printk(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall misc_register(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_410; // weak
_UNKNOWN unk_440; // weak
_UNKNOWN unk_470; // weak
_UNKNOWN unk_4A0; // weak
_UNKNOWN unk_4D0; // weak
miscdevice axi_fpga_misc_dev =
{
  0,
  "axi_fpga_dev",
  &axi_fpga_dev_fops,
  { &axi_fpga_dev_open, &axi_fpga_dev_open },
  &axi_fpga_dev_open,
  &axi_fpga_dev_open,
  &axi_fpga_dev_open,
  &axi_fpga_dev_open,
  0u
}; // idb
void *fpga_cache_store_addr; // idb


//----- (0000000000000000) ----------------------------------------------------
int __fastcall axi_fpga_dev_open(inode *inode, file *filp)
{
  return 0;
}

//----- (0000000000000008) ----------------------------------------------------
loff_t __fastcall axi_fpga_dev_llseek(file *filp, loff_t offset, int whence)
{
  if ( whence == 1 )
  {
    offset += filp->f_pos;
  }
  else if ( whence == 2 )
  {
    offset += 0x7FFFFFFLL;
  }
  else if ( whence )
  {
    return -22;
  }
  if ( (unsigned __int64)offset > 0x8000000 )
    return -22;
  filp->f_pos = offset;
  return offset;
}

//----- (0000000000000058) ----------------------------------------------------
int __fastcall axi_fpga_dev_mmap(file *filp, vm_area_struct *vma)
{
  unsigned __int64 vm_start; // x7
  unsigned __int64 vm_pgoff; // x6
  unsigned __int64 v4; // x5

  vm_start = vma->vm_start;
  vm_pgoff = vma->vm_pgoff;
  v4 = vma->vm_flags | 0x4044000;
  vma->vm_page_prot.pgprot = vma->vm_page_prot.pgprot & 0xFF9FFFFFFFFFFFE3LL | 0x60000000000000LL;
  vma->vm_flags = v4;
  return remap_pfn_range(vma, vm_start + vm_pgoff, 0x80000, 4096);
}
// 890: using guessed type int __fastcall remap_pfn_range(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000000A8) ----------------------------------------------------
ssize_t __fastcall axi_fpga_dev_read(file *f, char *buf, size_t len, loff_t *ppos)
{
  unsigned __int64 v4; // x5
  bool v5; // cc
  size_t v6; // x19
  unsigned __int64 v7; // x0
  ssize_t result; // x0
  __int64 v12; // x0

  v4 = *ppos;
  if ( buf )
    v5 = v4 > 0x7FFFFFF;
  else
    v5 = 1;
  if ( v5 )
    return -22;
  v6 = 0x8000000 - v4;
  v7 = *(_QWORD *)(_ReadStatusReg(SP_EL0) + 8);
  if ( 0x8000000 - v4 > len )
    v6 = len;
  if ( __CFADD__(buf, v6) || (unsigned __int64)&buf[v6] > v7 )
    return -14;
  v12 = _arch_copy_to_user(buf, (char *)fpga_cache_store_addr + v4, v6);
  if ( v12 == v6 )
    return -14;
  result = v6 - v12;
  *ppos += result;
  return result;
}
// 8A0: using guessed type __int64 __fastcall _arch_copy_to_user(_QWORD, _QWORD, _QWORD);

//----- (0000000000000168) ----------------------------------------------------
__int64 axi_fpga_dev_release()
{
  return 0;
}

//----- (0000000000000170) ----------------------------------------------------
// Alternative name is 'init_module'
int __cdecl axi_fpga_dev_init()
{
  __int64 v0; // x2
  int v1; // w20
  void *v2; // x0
  __int64 v3; // x2

  v1 = misc_register(&axi_fpga_misc_dev);
  if ( v1 < 0 )
  {
    printk(&unk_410, "axi_fpga_dev", v0);
  }
  else
  {
    v2 = (void *)memremap(939524096, 0x8000000, 1);
    fpga_cache_store_addr = v2;
    if ( v2 )
    {
      _memset_io(v2, 0, 0x8000000);
      v1 = 0;
      printk(&unk_470, "axi_fpga_dev", fpga_cache_store_addr);
      printk(&unk_4A0, "axi_fpga_dev", 939524096);
      printk(&unk_4D0, "axi_fpga_dev", 0x8000000);
    }
    else
    {
      printk(&unk_440, "axi_fpga_dev", v3);
      misc_deregister(&axi_fpga_misc_dev);
    }
  }
  return v1;
}
// 1A0: variable 'v0' is possibly undefined
// 1CC: variable 'v3' is possibly undefined
// 888: using guessed type __int64 __fastcall misc_deregister(_QWORD);
// 898: using guessed type __int64 __fastcall memremap(_QWORD, _QWORD, _QWORD);
// 8B0: using guessed type __int64 __fastcall _memset_io(_QWORD, _QWORD, _QWORD);
// 8B8: using guessed type __int64 __fastcall printk(_QWORD, _QWORD, _QWORD);
// 8C0: using guessed type __int64 __fastcall misc_register(_QWORD);

//----- (0000000000000270) ----------------------------------------------------
// Alternative name is 'cleanup_module'
void __cdecl axi_fpga_dev_exit()
{
  misc_deregister(&axi_fpga_misc_dev);
  memunmap(fpga_cache_store_addr);
}
// 888: using guessed type __int64 __fastcall misc_deregister(_QWORD);
// 8A8: using guessed type __int64 __fastcall memunmap(_QWORD);

// nfuncs=15 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
