//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t axi_fpga_dev_exit(void);
int32_t axi_fpga_dev_llseek(int32_t i_a1, int32_t i_a2, uint32_t i_a3,
                            int32_t i_a4, int32_t i_a5);
int32_t axi_fpga_dev_mmap(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t axi_fpga_dev_open(void);
int32_t axi_fpga_dev_read(int32_t i_a1, uint32_t i_a2, uint32_t i_a3,
                          int32_t i_a4);
int32_t axi_fpga_dev_release(void);
int32_t init_module(void);
int32_t unknown_964(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                    int32_t i_a5, int32_t i_a6, int32_t i_a7, int32_t i_a8);
int32_t unknown_97c(void);
int32_t unknown_b08(int32_t *p_a1);
int32_t unknown_b14(int32_t i_a1, int32_t i_a2, int32_t *p_a3);
int32_t unknown_b18(void);
int32_t unknown_b20(int32_t *p_a1, char *p_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_b24(int32_t i_a1);
int32_t unknown_bd8(int32_t *p_a1);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x14000000;   // 0x1
int32_t i_g2 = -0x4c3bb402;  // 0x1f
bool i_g3 = false;           // 0x2
int64_t i_g4;                // 0x20
int32_t i_g5 = -0x1c600000;  // 0x24
int32_t i_g6 = -0x1ed000e2;  // 0x28
int32_t i_g7 = 0x73253301;   // 0x3c1
int32_t i_g8 = 0x73253301;   // 0x3ea
int32_t i_g9;                // 0x4
int32_t i_g10 = -0x1caf0000; // 0x40
int32_t i_g11 = 0x73253601;  // 0x419
int32_t i_g12 = 0x1a000010;  // 0x44
int32_t i_g13 = 0x73253601;  // 0x446
int32_t i_g14 = 0x73253601;  // 0x473
int32_t i_g15;               // 0x4a0
int32_t i_g16 = 0x3520602;   // 0x4c
int32_t i_g17;               // 0x934

// ------------------------ Functions -------------------------

// Address range: 0x24 - 0x2c
int32_t axi_fpga_dev_open(void) {
    // 0x24
    return 0;
}

// Address range: 0x2c - 0x98
int32_t axi_fpga_dev_llseek(int32_t i_a1, int32_t i_a2, uint32_t i_a3,
                            int32_t i_a4, int32_t i_a5) {
    int32_t i_v1; // 0x2c
    if (i_a5 == (int32_t)&i_g1) {
        int32_t i_v2 = *(int32_t *)(i_a1 + (int32_t)&i_g12);        // 0x68
        int32_t i_v3 = *(int32_t *)(i_a1 + (int32_t)&i_g10) + i_a3; // 0x6c
        i_v1 = i_v2 + i_a4 + (int32_t)(i_v3 < i_a3);
    } else {
        if (i_a5 == (int32_t)&i_g3) {
            // 0x78
            i_v1 = (int32_t)(i_a3 > 0xffe00000) + i_a4;
        } else {
            // 0x40
            i_v1 = i_a4;
            if (i_a5 != 0) {
                // 0x58
                return -22;
            }
        }
    }
    // 0x48
    if (i_v1 != 0) {
        // 0x58
        return -22;
    }
    int32_t i_v4 = -22; // 0x50
    if (i_v4 >= 0x200000 != i_v4 != 0x200000) {
        // 0x54
        *(int32_t *)(i_a1 + (int32_t)&i_g10) = i_v4;
        *(int32_t *)(i_a1 + (int32_t)&i_g12) = 0;
    }
    // 0x58
    return i_v4;
}

// Address range: 0x9c - 0xe4
int32_t axi_fpga_dev_mmap(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    int32_t *p_v1 = (int32_t *)(i_a2 + (int32_t)&i_g6); // 0xa4
    *p_v1 = *p_v1 | 0x4044000;
    int32_t *p_v2 = (int32_t *)(i_a2 + (int32_t)&i_g5); // 0xbc
    int32_t i_v3 = *p_v2 & -61;                         // 0xc0
    *p_v2 = i_v3;
    int32_t i_v4 = *(int32_t *)(i_a2 + (int32_t)&i_g16); // 0xc8
    int32_t i_v5;                                        // 0x9c
    return unknown_964(i_a2, i_v4 + i_a2, 0xfe00, 0x200000, i_v3, i_a2, i_a3,
                       i_v5);
}

// Address range: 0xe4 - 0x1c0
int32_t axi_fpga_dev_read(int32_t i_a1, uint32_t i_a2, uint32_t i_a3,
                          int32_t i_a4) {
    // 0xe4
    int32_t i_v1; // 0xe4
    int32_t i_v2 = i_v1;
    int32_t i_v3;                                      // 0xe4
    uint64_t i_v4 = *(int64_t *)&i_v3;                 // 0xec
    int32_t i_v5 = i_v4;                               // 0xec
    uint32_t i_v6 = (int32_t)(i_v4 >> (int64_t)&i_g4); // 0xec
    i_v3 = 0;
    bool i_v7 = false; // 0x100
    bool i_v8 = true;  // 0x100
    if (i_v5 == 0) {
        i_v7 = i_v6 == 0x1fffff;
        i_v8 = i_v6 >= 0x1fffff;
    }
    bool i_v9 = i_v7 | !i_v8; // 0x108
    if (i_a2 == 0 || i_v8 == !i_v7 || i_v9) {
        int32_t i_v10 = i_v9 ? 0 : (int32_t)&i_g1;
        int32_t i_v11 = i_a2 == 0 ? (int32_t)&i_g1 : i_v10;
        i_v3 = i_v11;
        if (i_v11 != 0) {
            // 0x160
            return -22;
        }
    }
    uint32_t i_v12 = 0x200000 - i_v6; // 0x124
    int32_t i_v13 =
        ((i_v5 - (int32_t)(i_v6 > 0x200000)) % 2 != 0) < (i_v12 < i_a3) ? i_v12
                                                                        : i_a3;
    uint32_t i_v14 = i_v13 + i_a2; // 0x14c
    if (i_v14 < i_a2) {
        if (i_v2 != 0) {
            // 0x160
            return -14;
        }
    } else {
        if (i_v2 == -1 && i_v14 >= -2 - i_v2 + i_v14) {
            // 0x160
            return -14;
        }
    }
    // 0x168
    __asm_mrc(15, 0, i_v1, 3, 0, 0);
    __asm_mcr(15, 0, i_v1 & -13 | (int32_t)&i_g9, 3, 0, 0);
    __asm_isb();
    unknown_97c();
    __asm_mcr(15, 0, i_v1, 3, 0, 0);
    int32_t i_v15 = __asm_isb(); // 0x194
    if (i_v13 == i_v15) {
        // 0x160
        return -14;
    }
    uint64_t i_v16 = *(int64_t *)&i_v3;                  // 0x1a0
    uint32_t i_v17 = (int32_t)(i_v16 >> (int64_t)&i_g4); // 0x1a0
    int32_t i_v18 = i_v13 - i_v15;                       // 0x1a4
    uint32_t i_v19 = i_v18 + i_v17;                      // 0x1a8
    *(int32_t *)i_a4 = i_v19;
    *(int32_t *)(i_a4 + (int32_t)&i_g9) =
        (int32_t)(i_v19 < i_v17) + (int32_t)i_v16;
    return i_v18;
}

// Address range: 0x1c8 - 0x1d0
int32_t axi_fpga_dev_release(void) {
    // 0x1c8
    return 0;
}

// Address range: 0x1d0 - 0x280
int32_t init_module(void) {
    int32_t i_v1 = unknown_b24(1184); // 0x1d8
    int32_t i_v2;                     // 0x1d0
    if (i_v1 < 0) {
        // 0x1e4
        unknown_b20(&i_g7, "ltc_mem", i_v2, i_v2);
        // 0x1f0
        return i_v1;
    }
    int32_t i_v3 = unknown_b14(0xfe00000, 0x200000, &i_g1); // 0x208
    i_g17 = i_v3;
    int32_t i_v4; // 0x1d0
    if (i_v3 == 0) {
        // 0x218
        unknown_b20(&i_g8, "ltc_mem", (int32_t)&i_g1, i_v2);
        unknown_b08(&i_g15);
        i_v4 = i_v1;
    } else {
        // 0x230
        unknown_b18();
        int32_t i_v5 = i_g17; // 0x23c
        unknown_b20(&i_g11, "ltc_mem", i_v5, i_v5 >> (int32_t)&i_g2);
        unknown_b20(&i_g13, "ltc_mem", 0xfe00000, 0);
        unknown_b20(&i_g14, "ltc_mem", 0x200000, 0);
        i_v4 = 0;
    }
    // 0x1f0
    return i_v4;
}

// Address range: 0x2a0 - 0x2bc
int32_t axi_fpga_dev_exit(void) {
    // 0x2a0
    unknown_bd8(&i_g15);
    while (true) {
        // continue -> 0x2b8
    }
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.2.1)
// Detected functions: 7
